name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
        tag:
            default: ''
            required: false
#   release:
#     types: [released]

jobs:
  mirrorchyan:
    runs-on: macos-latest
    # if: ${{ github.repository_owner == 'ok-oldking' }}
    strategy:
      fail-fast: false
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "*Release-setup.exe"
          mirrorchyan_rid: ok-etheria
          tag: ${{ inputs.tag }}

          owner: ok-oldking
          repo: ok-etheria
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}